Easy calculaction for specific moduli
=====================================
v2026.158

In the instructions of this manual, sometimes a negative number needs to be reduced modulo N. In order to do this, add N as many times as necessary for the sum to become non-negative. Then this is the reduction result.

The 'alternating digit sum' ist the sum of digits (normally decimal, but binary digits in case of the binary variants) where every digit is multiplied with the weight +1 or -1. Start at the rightmost digit for which the weight is +1, then proceed backwards until the first digit has been processed. The weight has to be negated for every following step.

Example: The alternating digit sum of 123 = 3 * (+1) + 2 * (-1) + 1 * (+1) = 3 - 2 + 1 = 2.

Unless specified otherwise, the sections below operate on decimal digits. Binary numbers will always be specified with a "`0b`"-prefix.


Mod 3
-----

Take the digit sum and reduce recursively modulo 3.

Example:

31415 mod 3 = (3 + 1 + 4 + 1 + 5) mod 3 = 14 mod 3 = (1 + 4) mod 3 = 5 mod 3 = 2.


Binary variant
~~~~~~~~~~~~~~

Take the alternating digit sum, starting by adding the rightmost digit, and recursively reduce until the resulting sum is less than 0b11.

Example:

31415 mod 3 = 0b111101010110111 mod 0b11 = +1 - 1 + 1 - 1 + 0 - 1 + 0 - 1 + 0 - 1 + 1 - 0 + 1 - 1 + 1 = -1

-1 + 3 = 2

Note: In this calculation, the binary digits have been added in the reverse direction of the rule stated above. But this is OK because addition is commutative. That is, the order of integer additions does not change the result.


Mod 9
-----

Take the digit sum and reduce recursively modulo 9.


Mod 11
-----

Take the alternating digit sum and reduce recursively modulo 11.
