SSH
===
v2026.22


"no matching host key type"
---------------------------

If `ssh` issues an error message like the following when trying to connect

....
Unable to negotiate with 192.128.168.130 port 22: no matching host key type found. Their offer: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
....

You need to set the `HostKeyAlgorithms` option like this:

----
$ ssh -o HostKeyAlgorithms=rsa-sha2-512 root@192.128.168.130
----

In order to find out which algorithms your OpenSSH implementation supports, query a list of supported algorithms as follows:

----
$ ssh -Q HostKeyAlgorithms
----

Note that this argument is *not* documented for the -Q option. Instead, only some short names like "`kex`" are officially documented.

Nevertheless, `ssh -Q` takes most SSH configuration setting names which refer to algorithm selection as arguments also, mapping them automatically into the matching short name.

Here is an incomplete list of mappings from documented `-Q` arguments to SSH configuration setting names:

[options="header,autowidth"]
|====
| -Q argument | SSH Config Setting
| cipher      | Ciphers
| mac         | MACs
| kex         | KexAlgorithms
| key-sig     | HostKeyAlgorithms
| key-sig     | HostbasedAcceptedAlgorithms
| key-sig     | PubkeyAcceptedAlgorithms
| sig         | CASignatureAlgorithms
| kex-gss     | GSSAPIKexAlgorithms
|====

Note that some `-Q` arguments apply to multiple configuration settings.


Client Configuration
--------------------

My favourite `~/.ssh/config` default settings:

----
Host *
        #ProxyCommand -nnc6 $HOME/.ssh/proxy proxy 8080 %h %p
	HashKnownHosts no
        Compression yes
	Ciphers chacha20-poly1305@openssh.com,3des-cbc,aes256-gcm@openssh.com,aes256-ctr
	MACs hmac-ripemd160,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
	HostKeyAlgorithms ssh-rsa
        ControlPath none
        ControlPath ~/.ssh/shared_connections/%C
        ControlMaster auto
        ControlPersist 300
----


Connection sharing
------------------

Connection sharing enables using a single SSH connection to a particular destination host, port and user account, no matter how many `ssh`, `scp` or `sftp`-connections will be requested.

It can also be used to keep the connection open for some time after the last explicit connection has been closed, in case it shall be re-opened again. This can be very handy when the SSH server is started by inetd, because it avoids the relatively long startup time of `sshd`. It is also helpful if too many `scp` commands are run in rapid succession, because `inetd` might limit the number of allowed connections per time interval.

The entries starting with "`Control`" from the "`~/.ssh/config`"-settings shown above define defaults for connection sharing, but do not enable it yet.

In order to do so, copy the "`ControlPath`"-line which does *not* contain "`none`" into an earlier section of your "`~/.ssh/config`".

The connection defined in that section will then use connection sharing.

However, in order to actually work, the path mentioned in the `ControlPath` directive needs to be created first:

----
$ mkdir -m700 -- ~/.ssh/shared_connections
----

This needs only be done once for every ssh user which wants to use connection sharing. The SSH client will then automatically create and delete temporary socket special files in this directory.

Those sockets represent the currently existing established shareable connections, and the SSH client will automatically use them rather than creating new connections as long as they do exist.

If you want to terminate a connection immediately for some reason after closing your SSH session, without having to wait for the `ControlPersist` timeout:

----
$ ssh -O exit $DESTINATION
----

where $DESTINATION is rest of the previous `ssh` command which used the connection to be terminated immediately.

If you want to temporarily disable the connection sharing mechanism enabled for some connection by default and make a new un-shared connection without a `ControlPersist` timeout at its end:

----
$ ssh -o ControlPath=none $DESTINATION
----


SSH-connection through a proxy server
-------------------------------------

One might find oneself in the situation that one wants to establish an SSH connection to some host, but the SSH port of the destination host is blocked by the firewall of the local internet gateway.

In this case is possible to tunnel the SSH connection through a proxy server which uses an innocent port number that is not blocked by the local firewall, and this proxy will then connect to the actual target host.

Add the following option to your `ssh` command line:

----
-o ProxyCommand='socat STDIO PROXY:myproxy.test.com:%h:%p
----

This assumes the proxy is accessible as `http://myproxy.test.com:8080` - if a different port is used, say 3128, append the following immediately after the last character of the above `-o` argument:

----
,proxyport=3128
----

If the proxy needs a username "john" with password "secret" for authentication, add the following as well:

----
,proxyauth=john:secret
----


Non-interactively change SSH key password
-----------------------------------------

----
# Generate new password files out/*.psw for existing unprotected private key files out/*.prv:
for f in out/*.prv; do pwgen-with-entropy-harvesting-as-base62 > ${f%.*}.psw; done

# Create some helper scripts.
f=askpass && unexpand << '===' > $f && chmod +x $f
#! /bin/sh
xmessage -buttons "Send PSW,Send Empty,Cancel" "$1"
case $? in
        101) cat psw;;
        102) echo;;
        *) :
esac
===
f=sendpass && cat << '===' > $f && chmod +x $f
#! /bin/sh
cat $PWFILE
===

# Protect currently unprotected private keys out/*.prv with ChaCha20-poly1305 using passwords from files out/*.psw:
chmod u+w out/*.prv

for f in out/*.prv; do SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=./sendpass PWFILE=${f%.prv}.psw ssh-keygen -Z 'chacha20-poly1305@openssh.com' -p -f $f; done

chmod u-w out/*.prv

# Load the now-protected files into the current SSH agent:
for f in out/*.prv; do SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=./sendpass PWFILE=${f%.*}.psw ssh-add $f; done
----
