Video Conversion Tips
=====================
v2025.324.1


Display playback duration of a video file
-----------------------------------------

----
$ mediainfo --Inform='Video;%Duration/String1%' "${videofile:?}"
7 min 47 s 8 ms
----


Missing information like bitrate or duration
--------------------------------------------

Sometimes, when displaying the metadata of a `$videofile`, information is missing.

This can happen because some metadata is not calculated by tools like "`mediainfo`" but rather extracted from metadata tags which can be missing.

Most of those flags can be regenerated by converting $videofile with "`mkvmerge`" like this:

----
$ mkvmerge -o "${augmented_videofile}" "${videofile}"
----

After this, `$augmented_videofile` will hopefully provide the information missing from `$videofile`.


Repair a damaged video file
---------------------------

----
$ ffmpeg -hide_banner -loglevel error -err_detect ignore_err -i "${damaged_videofile:?}" -c copy -y "${repaired_videofile:?}"
----

If there are still errors like

....
Can't write packet with unknown timestamp
...
Terminating thread with return code -22 (Invalid argument)
....

one can try the following:

----
$ ffmpeg -hide_banner -loglevel error -fflags +genpts -err_detect ignore_err -i "${damaged_videofile:?}" -c copy -y "${repaired_videofile:?}"
----

However, `$repaired_videofile` may be heavily truncated in this case with its playback duration drastically reduced.


Combine VOB segments from a DVD to a single video file
------------------------------------------------------

Try this:

----
$ ffmpeg -i "concat:VTS_01_1.VOB|VTS_01_2.VOB|VTS_01_3.VOB|VTS_01_4.VOB|VTS_01_5.VOB|VTS_01_6.VOB" -map 0 -codec copy -dn -y "${output_videofile:?}"
----

This should generally work for assembling multiple short video clips into a larger video, and not just for `*.VOB` files.
