Pike
====
2025.22

The Pike stream cipher was invented by Ross Anderson to be a "leaner and meaner" version of FISH after he broke FISH in 1994. Its name is supposed to be a humorous allusion to the pike fish.

It is about 10% faster than FISH, yet believed to be much stronger. It potentially has a huge key length, and no attacks have been published as of 2004.

Pike consists of three lagged Fibonacci generators with relations

....
a[i] = mod(a[i - 55] + a[i - 24], 2 ^ 32)
b[i] = mod(b[i - 57] + b[i - 7], 2 ^ 32)
c[i] = mod(c[i - 58] + c[i - 19], 2 ^ 32)
....

The carries of the additions (before the modulo reduction) are compared in order to form a control decision.

The decision is true if at least one of the other two generators has the same carry bit value as the generator in question. Otherwise it is false.

This control decision has to be delayed for 8 cycles. Which means, the initial 8 cycles of the three generators have to be run unconditionally without producing output in order for the first control decision to "arrive". (An attacker knows that all generators are "on" in the initial 8 cycles, and could derive more information about the seed from any output than in later cycles.)

From now on, the delayed earlier control decision of every generator will be applied: If it was true, then the generator is updated for the next cycle. Otherwise the generator keeps is current value for the next cycle.

At the end of the current cycle, the next output of the algorithm is the 16 low-order bits of the XOR of the current values of all three generators.

Then the algorithm repeats by running all three generators again for one cycle, forming the next control decision.

Obviously, the endianness how to output the 16 result bits must be decided and declared by an implementation.

The key of the generator is the initial state of the three 32-bit arrays `a[55]`, `b[75]` and `c[58]`, i.e. 6016 bit.

As usual for this kind of generators, at least one of the seed words in each array must be odd. I suggest setting the LSB of the element in the middle of the arrays to 1 if all entries of the seed array are even.

Also the seed values should already look "random", because if an array were filled with only small values, the associated generator needed a lot of time to "warm up" and start producing random-looking values.

It might be a good idea to throw away the first few iterations over the largest of the arrays anyway, in case the seed values contain recognizable patterns.

Experimentation has shown that about 2000 cycles of the generator are sufficient to recover even from the worst seed, that is all seed array entries being zero (before setting the LSB of the element in the middle to 1 as suggested above).

Adding about 50 % to that number just to be sure, I recommend to throw away the results of the first 3072 cycles before starting to produce actual output. Then one does not need to concern oneself with the bit pattern distribution of the seed. Of course, sufficient entropy is still required for a secure key.

Hint for carry calculation: Carry is 1 if the sum after modulo reduction is smaller than any of its input values. (This will then actually apply to both inputs, so it does not matter which input is compared and there is no need to also compare the other one.)

A problem with PIKE is that the description in its original paper leaves some room for interpretation. The above description is the best I could make of that description.

However, this also means my interpretation could be wrong, and thus the above description.

The situation is worsened by the fact that no test vectors have been published, let alone a reference implementation.

But this might also mean that the cipher is in fact so strong that the NSA does not want it to be widely used, because they have no chance cracking it. Therefore, details about the cipher might have been intentionally published vaguely, disencouraging anyone from actually using it.

The algorithm's paper has "appeared" on FSE3 in 1996 as part of publication LNCS 1039. However, I could it not find it in the list of published material of that conference.
